"""rename address

Revision ID: d4cfbf235777
Revises: 6416aff4086a
Create Date: 2024-11-07 17:39:24.887422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cfbf235777'
down_revision = '6416aff4086a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # with op.batch_alter_table('departments', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
    #     batch_op.drop_column('address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # with op.batch_alter_table('departments', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
    #     batch_op.drop_column('location')
    # ### end Alembic commands ###
